# Generated by Django 4.0.3 on 2022-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_team',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='create_team',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
