# Generated by Django 4.0.3 on 2022-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_trainer_task_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_task',
            name='task_progress',
            field=models.IntegerField(default=0),
        ),
    ]
