# Generated by Django 4.0.3 on 2022-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_probation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='probation',
            name='stop_reason',
            field=models.TextField(default=''),
        ),
    ]
