# Generated by Django 4.0.3 on 2022-04-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_probation_stop_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='trainee_delay',
            field=models.IntegerField(default=0),
        ),
    ]
