# Generated by Django 4.0.3 on 2022-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_test_status_git_commit_test_status_git_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_taskassign',
            name='git_link',
            field=models.TextField(default='', null=True),
        ),
    ]
