# Generated by Django 4.0.3 on 2022-04-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_project_taskassign_git_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='signature',
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='pending_status',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='create_team',
            name='trainer_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='git_commit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='git_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='confirm_salary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='confirm_salary_status',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='hr_designation',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='project_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('module_name_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_table_name', to='base_app.project_modules')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_table_name', to='base_app.project_taskassign')),
            ],
        ),
        migrations.CreateModel(
            name='project_module_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_name_name', to='base_app.project_modules')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_name', to='base_app.project_taskassign')),
            ],
        ),
    ]
