# Generated by Django 4.0.3 on 2022-04-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_alter_project_table_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_module_assign',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
