# Generated by Django 4.0.3 on 2022-05-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_alter_project_table_module_name_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project_modules',
        ),
    ]
