# Generated by Django 4.0.2 on 2022-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='pay_status',
            field=models.IntegerField(default=0),
        ),
    ]
