# Generated by Django 4.0.2 on 2022-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_income_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='account_no',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='bank_branch',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='da',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='ifsc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='other_allovance',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='other_allovancetype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='net_salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
