# Generated by Django 4.0.2 on 2022-05-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_leave_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='days',
        ),
    ]
