# Generated by Django 4.0.2 on 2022-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0024_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='confirm_salary',
            field=models.IntegerField(default=0),
        ),
    ]
