# Generated by Django 4.0.2 on 2022-06-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0025_alter_user_registration_confirm_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='confirm_salary',
            field=models.IntegerField(default=''),
        ),
    ]
