# Generated by Django 4.0.2 on 2022-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0026_alter_user_registration_confirm_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promissory',
            name='final_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
