# Generated by Django 4.0.2 on 2022-06-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0027_alter_promissory_final_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promissory',
            name='final_due_date_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promissory',
            name='second_due_date_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
