# Generated by Django 4.0.2 on 2022-06-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0029_alter_promissory_final_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promissory',
            name='final_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_due_date_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_date_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
