# Generated by Django 4.0.1 on 2022-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0032_alter_promissory_final_total_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='confirm_salary',
            field=models.IntegerField(default='0'),
        ),
    ]
