# Generated by Django 4.0.3 on 2022-05-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
    ]
